// `.env.ts` is generated by the `npm run env` command
// import env from './.env.json';

export const environment = {
  production: true,
  version: '1.0.0',
  serverUrl: '',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
